### ISSUE TITLE
[CNFs] Update Envoy CNF to add public helm chart support

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#186]
[Acceptance Criteria](https://github.com/cncf/cnf-conformance/issues/186#issuecomment-621482006)

### [CNFs] Update Envoy CNF to add public helm chart support
---

Documentation tasks:
- [ ]  TBD

Implementation tasks:
- [x] add support for public helm chart re: #169 
- [x] Tag 1 or more people to peer review

CNF Testing task:
- [x]  Follow the new example CNF's README.md to test the CNF
- [x]  Add the Final Score in a comment in this ticket
- [x]  Add the entire test result output in a comment in this ticket

**QA tasks**

Dev Review: 
- [x] walk through A/C
- [x] do you get the expected result?
- [x] if yes, 
   - [x] move to `Needs Peer Review` column  
   - [x] create Pull Request and follow check list
   - [x] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [x] walk through A/C
- [x] do you get the expected result?
- [x] if yes, 
   - [x] move to `Reviewer Approved` column
   - [x] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by lixuna** [comment]
Acceptance criteria: steps to test during development and peer review
---

- [ ]  I can follow the set up instructions as a `CNF Developer` https://github.com/cncf/cnf-conformance/blob/master/INSTALL.md#cnf-developer-install-and-usage-guide
- [ ]  I should see a Envoy CNF example folder
    - [ ]   Ie. in an example-cnfs folder with each example CNF having it’s own sub-folder with a config
- [ ]  I should see Envoy CNF README with summary and instructions in Envoy directory and in example CNFs
- [ ]  I should see a cnf-conformance.yml configuration in the Envoy example CNF folder
- [ ]  I can run the CNF Conformance Tests w/ the Envoy CNF
- [ ]  I can check the output of the CNF conformance command
   - [ ]  I should see which tests passed or failed for the Envoy CNF
   - [ ]  I should see a final score for the Envoy CNF
- [ ]  Final Score for Linkerd2 CNF = 


Testing A/C task:
- [ ]  Add the Final Score in a comment in this ticket
- [ ]  Add the entire test result output in a comment in this ticket

**Comment by nupejosh** [comment]
Final score from running `crystal src/cnf-conformance.cr all` is 62

**Entire test result output**
```
name: cnf conformance
status:
points:
items:
- name: privileged
  status: passed
  points: 5
- name: increase_capacity
  status: passed
  points: 10
- name: decrease_capacity
  status: passed
  points: 10
- name: ip_addresses
  status: failed
  points: -1
- name: liveness
  status: passed
  points: 5
- name: readiness
  status: passed
  points: 5
- name: rolling_update
  status: passed
  points: 5
- name: nodeport_not_used
  status: passed
  points: 5
- name: install_script_helm
  status: passed
  points: 5
- name: helm_chart_valid
  status: passed
  points: 5
- name: helm_chart_published
  status: passed
  points: 5
- name: helm_deploy
  status: failed
  points: -1
- name: reasonable_image_size
  status: failed
  points: -1
- name: reasonable_startup_time
  status: passed
  points: 5
```
