### ISSUE TITLE
[Beta Test] Create clusters for beta testing

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-conformance#238]
## Description

clusters needed for beta testing cnf conformance test

---

Tasks:
- [x] Determine smallest cluster sized required for MVP = 2 nodes, 1 master and 1 worker
- [x] Determine smallest machine size needed = t1.small works as expected for MVP set of tests. (Any *.small)
- [x] Spin up required number of clusters in AMS1 and EWR1 facillities
    - [x] Create 6 clusters in AMS1
    - [x] Create 5 clusters in EWR1
    - Using CNF Testbed tooling (+k8s-infra)
    - [x] Split load across facilities AMS1 and EWR1
       - [x] 6 clusters in AMS1
       - [x] 5 clusters in EWR1
    - [x] 1 cluster for each tester
    - [x] 11 testers total = 11 clusters =   22 nodes (machines)
- [x] Save kubeconfig files to secure location
- [x] Test access to each cluster using `kubectl cluster-info` and KUBECONFIG environment set for each cluster
- [x] Add comment with cluster name and IP info to this ticket for each cluster

**Comment by agentpoyo** [comment]
Created a 2 host cluster, 1 master 1 worker using t1.small size for the hosts.

```
  hosts:
    node0:
      ansible_host: 139.178.88.159
      ip: 139.178.88.159
      access_ip: 139.178.88.159
    node1:
      ansible_host: 139.178.88.253
      ip: 139.178.88.253
      access_ip: 139.178.88.253
```
