### ISSUE TITLE
[Feature] Use a generated release name for helm

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-conformance#503]
**Is your feature request related to a problem? Please describe.**

Helm release name is tightly coupled with the sandbox directory structure

**Describe the solution you'd like**
- Remove deployment_name, deployment_label, and release_name from the cnf-conformance.yml
- NOTE: deployment_name is currently used as the name of the directory  the cnfs sandbox directory
- Use a generated release name for helm
- NOTE: manifest-file-only cnfs don't need a release name
- Generate release name based on all of the workload resource metadata names (or generatedName) 
- Make the cnfs/<directory> be the generated name
- Use the cnfs/<directory> (for helm installs) as the release name

**Describe alternatives you've considered**

**Additional context**

**Comment by lixuna** [comment]
FYI - This enhancement has been included in v1.10.0. If any issues are found during peer review, please open a new bug ticket.

**Comment by agentpoyo** [comment]
This looks good. You can see in `get pods` there is a generated name for wordpress when not specifying a name for deployment_name, deployment_label, and release_name in the cnf-conformance.yml

```
$ kubectl get pods
NAME                                        READY   STATUS    RESTARTS   AGE
chaos-controller-manager-7f9bbd476f-xzn9g   1/1     Running   0          164m
chaos-daemon-2rm2m                          1/1     Running   0          164m
cri-tools-hrdc8                             1/1     Running   0          22d
wordpress-1611088866-575c94bcd7-d27kv       1/1     Running   0          80s
wordpress-1611088866-mariadb-0              1/1     Running   0          80s
```
Original file:
```
---
git_clone_url: 
install_script: 
release_name: 
deployment_name: 
deployment_label: 
service_name: bitnami-wordpress 
application_deployment_names: [bitnami-wordpress]
docker_repository:
helm_repository:
  name: stable 
  repo_url: https://charts.bitnami.com/bitnami
helm_chart: bitnami/wordpress
helm_chart_container_name: wordpress
white_list_helm_chart_container_names: [falco, node-cache, nginx, coredns, calico-node, kube-proxy, nginx-proxy, kube-multus]

container_names: 
  - name: wordpress
    rolling_update_test_tag: "10.4.4"
    rolling_downgrade_test_tag: 10.4.3
    rolling_version_change_test_tag: latest
    rollback_from_tag: latest
```

Generated file update after running cnf_setup:
```
---
git_clone_url:
install_script:
release_name: wordpress-1611088866
deployment_name:
deployment_label:
service_name: bitnami-wordpress
application_deployment_names:
- bitnami-wordpress
docker_repository:
helm_repository:
  name: stable
  repo_url: https://charts.bitnami.com/bitnami
helm_chart: bitnami/wordpress
helm_chart_container_name: wordpress
white_list_helm_chart_container_names:
- falco
- node-cache
- nginx
- coredns
- calico-node
- kube-proxy
- nginx-proxy
- kube-multus
container_names:
- name: wordpress
  rolling_update_test_tag: 10.4.4
  rolling_downgrade_test_tag: 10.4.3
  rolling_version_change_test_tag: latest
  rollback_from_tag: latest
```
